### ISSUE TITLE
isActive function doesn't work when scrolling up from "outside" of section

### ISSUE THREAD

**Issue by patrykkurzeja91** [smastrom/vue-use-active-scroll#1]
Hey, I was looking for some lib to make active-scroll functionality and this one is really nice 💪🏻 

I found small bug though - when scrolling to the bottom of the page and moving out of activated sections, isActive doesn't work until You scroll up back to top or just start scrolling down when within active-scroll section. 

![gify](https://user-images.githubusercontent.com/29832994/215486889-b4cd8b28-8bb3-45a2-a51e-4e20dbf43762.gif)

**Comment by smastrom** [comment]
Hi @patrykkurzeja91, I must admit that you spotted an important scenario that I missed.

What's going to happen bottom is not reached and items are offscreen? What if jumpToLast is false?

I created a new branch named `fix-jumpToLast` where you can see the new code.

A preview of the new website is available at: [https://fix-jumptolast--clever-mandazi-81a9b5.netlify.app/](https://fix-jumptolast--clever-mandazi-81a9b5.netlify.app/).

I'll release a new version this evening once I get back home.

Thank you!

**Comment by smastrom** [comment]
Hi @patrykkurzeja91, I just released Vue Use Active Scroll v0.9.7. Check the release notes [here](https://github.com/smastrom/vue-use-active-scroll/releases/tag/v0.9.7).

I'll close this issue. Please feel free to reopen if you still face issues.

And obviously, thank your for raising it in first place.

Have a nice tuesday!

Simone
