### ISSUE TITLE
`HTMLElement is not defined` on Nuxt (SSR)

### ISSUE THREAD

**Issue by ojvribeiro** [smastrom/vue-use-active-scroll#6]
There's an error occorring on Nuxt 3 using this lib on SSR mode.

Minimal reproduction: https://stackblitz.com/edit/nuxt-starter-xtdjhc?file=app.vue

On Stackblitz the error can only be seen on terminal (not breaking the application):

> ![image](https://github.com/smastrom/vue-use-active-scroll/assets/8026741/5414ed7b-cc4c-4e9d-b27d-c63c50b643ab)

On local and production, this error is shown as an error 500, thus breaking the execution of the app:

> ![image](https://github.com/smastrom/vue-use-active-scroll/assets/8026741/7eb09798-5b16-449c-aa5d-4313146d1984)

----

The current workaround is by wrapping the loop of links with a `<ClientOnly>` Nuxt component.

```html
<ClientOnly>
  <ul class="flex flex-col gap-4 whitespace-nowrap">
    <li v-for="link in links" :key="link.href">
      <NuxtLink
        :to="`#${link.href}`"
        class="-m-3 p-3 transition-colors"
        :class="[
          isActive(link.href)
            ? 'cursor-default text-primary'
            : 'text-neutral-200 hover:text-neutral-400',
        ]"
      >
        {{ link.label }}
      </NuxtLink>
    </li>
  </ul>
</ClientOnly>
```

**Comment by smastrom** [comment]
Hi @ojvribeiro, thank you very much for raising the issue (and providing a reproduction).

I'll be releasing a fix in the next 30 minutes or so. In the meanwhile, you should be able to overcome the issue by using `activeId` instead of `isActive`.

```vue
<NuxtLink
  :to="`#${link.href}`"
  class="-m-3 p-3 transition-colors"
  :class="[
    activeId === link.href
      ? 'cursor-default text-primary'
      : 'text-neutral-200 hover:text-neutral-400',
  ]"
>
  {{ link.label }}
</NuxtLink>
```

Thank you again!

**Comment by ojvribeiro** [comment]
Oh, that was fast 😄 

Thanks a lot for the better workaround and the quick response.

**Comment by smastrom** [comment]
Hi @ojvribeiro, please update to the new version:

`pnpm add vue-use-active-scroll@latest`

Cheers!
