### ISSUE TITLE
Losing active scroll when dragging the scrollbar

### ISSUE THREAD

**Issue by patrick-hurley** [smastrom/vue-use-active-scroll#7]
Hi there, firstly thank you for creating this repo it's really useful! 

I've noticed that once you click an anchor link, and then try to drag the scrollbar using a 'click and drag' with your mouse, the active link doesn't update anymore when you're scrolling the page. It starts behaving correctly again if you then click another link, or use a mouse wheel or touchpad drag instead. I can reproduce this on the demo page, as well as on my own integration.

Reproduced on Mac using Chrome and Firefox. Interestingly on Firefox the issue only occurs if the content has scrolled fully to the start or end of the page.

**Comment by smastrom** [comment]
Hi @patrick-hurley, I am having troubles trying to reproduce this:

> and then try to drag the scrollbar using a 'click and drag' with your mouse

Can you please capture a screen recording using the [Demo](https://vue-use-active-scroll.netlify.app/) website?

**Comment by smastrom** [comment]
xHi @patrick-hurley, sorry but I cannot reproduce this:

> and then try to drag the scrollbar using a 'click and drag' with your mouse

Can you please capture a screen recording using the [Demo](https://vue-use-active-scroll.netlify.app/) website?

**Comment by patrick-hurley** [comment]
Hi @smastrom. Sure, here's a video recording on Mac with Chrome.

https://github.com/user-attachments/assets/8b1c8220-7032-47bc-a27f-0d4c4b517c59

**Comment by smastrom** [comment]
Thank you, I'll release a fix soon.
